## Task 1

In [ ]:
Import the following modules: “math”, “keras”, “bqplot“, “numpy“

In [ ]:
import math
import keras
import numpy as np
import pandas 
!pip install bqplot

import bqplot
from sklearn.preprocessing import MinMaxScaler




     |████████████████████████████████| 1.2 MB 22.9 MB/s 


In [ ]:
#Test your function with requested example if available

In [ ]:
#Make one more test for your function

## Task 2

In [ ]:
Write a function, which assigns a 25% discount to a product given a price. 
Approximate the result up to 2 decimal places

In [ ]:
def discount(price):
  price=price-(price/100)*25
  print(price)


In [ ]:
discount(12000)

9000.0


## Task 3

In [ ]:
Write a function, which finds the sum of three numbers, return always integer. Input 
parameter can be of types float or integer

In [ ]:
def sum(num1,num2,num3):
  sum=num1+num2+num3
  print(int(sum))

In [ ]:
sum(25.4,25,24)

74


In [ ]:
#Make one more test for your function

In [ ]:
#Make one more test for your function

## Task 4

In [ ]:
A super_calculator function gets two integer numbers (num1,num2) and returns 
results by performing addition (num1+num2), subtraction (num1-num2), 
multiplication (num1*num2), division (num1/num2) and comparison (num1>num2) 
as a tuple. Round the float numbers up to 3 decimal places 

In [ ]:
def super_calculator(num1,num2):
  addition=num1+num2
  subtraction=num1-num2
  multiplication=num1*num2
  division=num1/num2
  comparison=num1>num2
  mytuple=((addition),(subtraction),format(division,".3f"),multiplication,comparison)
  print(mytuple)


In [ ]:
super_calculator(6,3)

(9, 3, '2.000', 18, True)


In [ ]:
#Make one more test for your function

## Task 5

In [ ]:
Write a function ‘combine_tuples’, which combines three tuples concatenating 
the elements with the same indices and returns a list. 

In [ ]:
def combine_tuples(mytuple1,mytuple2,mytuple3):
  list=[]
  for index in range(len(mytuple1)):
    temp=mytuple1[index]+mytuple2[index]+mytuple3[index]
    list.append(temp)
  print(list)  

In [ ]:
combine_tuples(("hello","hi","hey"),('am','am','am'),('faateih','saqib','qasim'))

['helloamfaateih', 'hiamsaqib', 'heyamqasim']


In [ ]:
#Make one more test for your function

## Task 6

In [ ]:
Write a function, which returns the factorial of the given arguments in a dictionary, 
with original element as a key and its factorial as a value. 

In [ ]:
def factorial(*args):
  dict={}
  for x in args:
    if x < 0:
     print("Sorry, factorial does not exist for negative numbers")
    elif x == 0:
     print("The factorial of 0 is 1")
    else:
     fact=1
     for i in range(1,x + 1):
      fact = fact*i
    dict[x]=fact
  print(dict)      




In [ ]:
factorial(1,2,5)

{1: 1, 2: 2, 5: 120}


In [ ]:
#Make one more test for your function

## Task 7

In [ ]:
Complete the code of the class Cube, which finds its the volume. 

In [ ]:
class Cube(): 
 def __init__(self, length): 
  self.length=length
 def cube_volume(self): 
  print(self.length)
  volume=(self.length)*(self.length)*(self.length)
  print(volume) 

In [ ]:
newCube = Cube(19) 
newCube.cube_volume()

19
6859


## Task 8

In [ ]:
Write a function, which checks whether all elements of two numpy arrays are 
equal

In [ ]:
def equality(nparray,nparray2):
  bol=np.array_equal(nparray,nparray2)
  print(bol)



In [ ]:
equality([1,2,3],[1,2,4])

False


In [ ]:
#Make one more test for your function

In [ ]:
#Make one more test for your function

# Task 9

In [ ]:
Write a function, which normalizes a 3x3 randomly generated matrix (maximal 
element after normalization should be 1, minimal should be 0, other should be 
proportional to them).

In [ ]:
def normalize():
  
  array1=np.random.rand(3,3)
  print(array1)
  xmax, xmin = array1.max(), array1.min()
  array1 = (array1 - xmin)/(xmax - xmin)
  print(array1)
  

In [ ]:
normalize()

[[0.6989544  0.95317544 0.2156656 ]
 [0.56541367 0.94019242 0.40483796]
 [0.32488815 0.93232032 0.72744125]]
[[0.65529811 1.         0.        ]
 [0.47422834 0.98239614 0.25650147]
 [0.1480964  0.97172224 0.69392383]]


In [ ]:
#Make one more test for your function

# Task 10

In [ ]:
Write a function, which returns average, standard deviation and variance of a 
numpy array as a tuple.

In [ ]:
def rsv(array1):
  sd=np.std(array1)
  vari=np.var(array1)
  average=np.average(array1)
  mytuple=(sd,vari,average)
  print(mytuple)


In [ ]:
rsv([10,20,30])

(8.16496580927726, 66.66666666666667, 20.0)


In [ ]:
#Make one more test for your function

## Task 11

In [ ]:
Write a function, which returns all dates on specified month, given the target 
month and the next one. 

In [ ]:
def dates(sdate,edate):
 days=pandas.date_range(sdate,edate)
 print(days)

In [ ]:
dates('2012-07', '2012-08')

DatetimeIndex(['2012-07-01', '2012-07-02', '2012-07-03', '2012-07-04',
               '2012-07-05', '2012-07-06', '2012-07-07', '2012-07-08',
               '2012-07-09', '2012-07-10', '2012-07-11', '2012-07-12',
               '2012-07-13', '2012-07-14', '2012-07-15', '2012-07-16',
               '2012-07-17', '2012-07-18', '2012-07-19', '2012-07-20',
               '2012-07-21', '2012-07-22', '2012-07-23', '2012-07-24',
               '2012-07-25', '2012-07-26', '2012-07-27', '2012-07-28',
               '2012-07-29', '2012-07-30', '2012-07-31', '2012-08-01'],
              dtype='datetime64[ns]', freq='D')


In [ ]:
#Make one more test for your function

## Task 12

In [ ]:
Write a function, which compares elements of the two pandas Series of the same 
size, return bool (True if all elements are equal).

In [ ]:
def compare(series1,series2):
 ps1 = pandas.Series(series1)
 ps2 = pandas.Series(series2)
 result = ps1.equals(other=ps2)
 print(result)

In [ ]:
compare([1,2,3],[1,2,3])

True


In [ ]:
#Make one more test for your function

# Task 13

In [ ]:
Write a function, which assigns new string indices to the given DataFrame. The 
DataFrame and new string indices should be parameters of the function

In [ ]:
students = [['jack', 34, 'Sydeny', 'Australia',85.96],
            ['Riti', 30, 'Delhi', 'India',95.20],
            ['Vansh', 31, 'Delhi', 'India',85.25],
            ['Nanyu', 32, 'Tokyo', 'Japan',74.21],
            ['Maychan', 16, 'New York', 'US',99.63],
            ['Mike', 17, 'las vegas', 'US',47.28]]
index=['a', 'b', 'c', 'd', 'e', 'f']


def newind(data,index):
   df = pandas.DataFrame(data,index=index  )
   df
   print(df)


In [ ]:
newind(students,index)
 


         0   1          2          3      4
a     jack  34     Sydeny  Australia  85.96
b     Riti  30      Delhi      India  95.20
c    Vansh  31      Delhi      India  85.25
d    Nanyu  32      Tokyo      Japan  74.21
e  Maychan  16   New York         US  99.63
f     Mike  17  las vegas         US  47.28


True


In [ ]:
#Make one more test for your function

# Task 14

In [ ]:
Write a function, which extracts a part of data from a DataFrame on given column 
and row range (parameters of the function should be DataFrame, col_start, 
col_end, row_start, row_end)

In [31]:
students = [['jack', 34, 'Sydeny', 'Australia',85.96],
            ['Riti', 30, 'Delhi', 'India',95.20],
            ['Vansh', 31, 'Delhi', 'India',85.25],
            ['Nanyu', 32, 'Tokyo', 'Japan',74.21],
            ['Maychan', 16, 'New York', 'US',99.63],
            ['Mike', 17, 'las vegas', 'US',47.28]]



def new(data,col_start,col_end,row_start,row_end):
   df = pandas.DataFrame(data)
   new=df.iloc[row_start:row_end,col_start:col_end]
   print(new)


In [32]:
new(students,0,4,2,4)
 


       0   1      2      3
2  Vansh  31  Delhi  India
3  Nanyu  32  Tokyo  Japan


In [ ]:
#Make one more test for your function

# Task 15

In [ ]:
Write a function, which returns a DataFrame by merging of two DataFrames 
horizontally. The result has columns from both DataFrames

In [36]:
students = [['jack', 34, 'Sydeny', 'Australia',85.96],
            ['Riti', 30, 'Delhi', 'India',95.20],
            ['Vansh', 31, 'Delhi', 'India',85.25],
            ['Nanyu', 32, 'Tokyo', 'Japan',74.21],
            ['Maychan', 16, 'New York', 'US',99.63],
            ['Mike', 17, 'las vegas', 'US',47.28]]


students2=[['Nanyu', 32, 'Tokyo', 'Japan',74.21],
            ['Maychan', 16, 'New York', 'US',99.63],
            ['Mike', 17, 'las vegas', 'US',47.28]]


def merge(first,second):
  f=pandas.DataFrame(first)
  s=pandas.DataFrame(second)
  result = pandas.concat([f, s], axis=1)
  print(result)





In [37]:
merge(students,students2)
 


         0   1          2          3      4        0     1          2      3  \
0     jack  34     Sydeny  Australia  85.96    Nanyu  32.0      Tokyo  Japan   
1     Riti  30      Delhi      India  95.20  Maychan  16.0   New York     US   
2    Vansh  31      Delhi      India  85.25     Mike  17.0  las vegas     US   
3    Nanyu  32      Tokyo      Japan  74.21      NaN   NaN        NaN    NaN   
4  Maychan  16   New York         US  99.63      NaN   NaN        NaN    NaN   
5     Mike  17  las vegas         US  47.28      NaN   NaN        NaN    NaN   

       4  
0  74.21  
1  99.63  
2  47.28  
3    NaN  
4    NaN  
5    NaN  


In [ ]:
#Make one more test for your function